using System.Diagnostics.CodeAnalysis;
using BlazorBlueprint.Primitives.Utilities;
using Microsoft.AspNetCore.Components;
using Microsoft.JSInterop;

namespace BlazorBlueprint.Primitives.Sortable;

/// <summary>
/// A headless drag-and-drop sortable primitive powered by Sortable.js.
/// </summary>
/// <remarks>
/// <para>
/// Provides all the behavioral functionality for sortable lists: JS interop lifecycle,
/// event callbacks, accessibility (ARIA live announcements), and stable Blazor diffing
/// via automatic <c>@key</c> wrappers. Ships no CSS — styling is the responsibility of
/// the consuming component or the styled <c>BlazorBlueprint.Components.BbSortable</c> wrapper.
/// </para>
/// <para>
/// Supports single lists, connected multi-lists (items move between lists via shared
/// <see cref="Group"/> names), and any visual layout.
/// </para>
/// </remarks>
/// <typeparam name="TItem">The type of items in the sortable list.</typeparam>
public partial class BbSortable<TItem> : ComponentBase, IAsyncDisposable
{
    private IJSObjectReference? _module;
    private DotNetObjectReference<BbSortable<TItem>>? _ref;
    private string _liveAnnouncement = string.Empty;
    private bool _jsInitialized;
    private bool _needsReinit;

    // Track previous config values for re-initialization detection
    private string _prevGroup = string.Empty;
    private string? _prevPull;
    private bool _prevPut = true;
    private bool _prevSort = true;
    private string _prevHandle = string.Empty;
    private string? _prevFilter;
    private bool _prevForceFallback = true;

    [Inject]
    private IJSRuntime JsRuntime { get; set; } = null!;

    /// <summary>
    /// Gets or sets the render fragment used to display each item.
    /// The <c>context</c> parameter provides the data item of type <typeparamref name="TItem"/>.
    /// </summary>
    [Parameter]
    public RenderFragment<TItem>? ItemTemplate { get; set; }

    /// <summary>
    /// Gets or sets the list of items to render and sort.
    /// </summary>
    [Parameter, AllowNull]
    public IList<TItem> Items { get; set; }

    /// <summary>
    /// Raised when an item is reordered within this list.
    /// The tuple provides the original index and the new index after the move.
    /// </summary>
    [Parameter]
    public EventCallback<(int OldIndex, int NewIndex)> OnUpdate { get; set; }

    /// <summary>
    /// Raised when an item is dragged out of this list into another connected list.
    /// The tuple provides the item's original index in this list and its landing index
    /// in the target list.
    /// </summary>
    [Parameter]
    public EventCallback<(int OldIndex, int NewIndex)> OnRemove { get; set; }

    /// <summary>
    /// Raised when an item from a connected list is dropped into this list.
    /// The tuple provides the item's original index in the source list and its
    /// landing index in this list.
    /// </summary>
    /// <remarks>
    /// Use alongside <see cref="OnRemove"/> on the source list to coordinate cross-list
    /// moves: in the <see cref="OnRemove"/> handler remove the item from the source and
    /// store it; in the <see cref="OnAdd"/> handler insert the stored item into this list.
    /// </remarks>
    [Parameter]
    public EventCallback<(int OldIndex, int NewIndex)> OnAdd { get; set; }

    /// <summary>
    /// Gets or sets the HTML element id for the sortable container.
    /// Auto-generated by default.
    /// </summary>
    [Parameter]
    public string Id { get; set; } = IdGenerator.GenerateId("sortable");

    /// <summary>
    /// Gets or sets the Sortable.js group name used to connect multiple lists.
    /// Lists sharing the same group name can exchange items.
    /// Defaults to a unique value (isolated list).
    /// </summary>
    [Parameter]
    public string Group { get; set; } = IdGenerator.GenerateId("sortable-group");

    /// <summary>
    /// Gets or sets the pull behaviour for the group.
    /// Use <c>"clone"</c> to copy items instead of moving them,
    /// or <c>null</c> (default) to move them.
    /// </summary>
    [Parameter]
    public string? Pull { get; set; }

    /// <summary>
    /// Gets or sets whether items from connected lists can be dropped into this one.
    /// Defaults to <c>true</c>.
    /// </summary>
    [Parameter]
    public bool Put { get; set; } = true;

    /// <summary>
    /// Gets or sets whether items within this list can be reordered.
    /// Set to <c>false</c> to create a list that only accepts items from other lists.
    /// Defaults to <c>true</c>.
    /// </summary>
    [Parameter]
    public bool Sort { get; set; } = true;

    /// <summary>
    /// Gets or sets a CSS selector used as the drag-handle element inside each item.
    /// When set, only the matched child element initiates a drag.
    /// </summary>
    [Parameter]
    public string Handle { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets a CSS selector for child elements that cannot be dragged.
    /// </summary>
    [Parameter]
    public string? Filter { get; set; }

    /// <summary>
    /// Gets or sets whether to use a software fallback renderer instead of the
    /// browser's native HTML5 drag-and-drop API.
    /// Defaults to <c>true</c> for consistent cross-browser behaviour.
    /// </summary>
    [Parameter]
    public bool ForceFallback { get; set; } = true;

    /// <summary>
    /// Gets or sets an accessible label for the sortable container,
    /// exposed as <c>aria-label</c> on the container element.
    /// </summary>
    [Parameter]
    public string? AriaLabel { get; set; }

    /// <summary>
    /// Gets or sets any additional HTML attributes to apply to the container element.
    /// </summary>
    [Parameter(CaptureUnmatchedValues = true)]
    public Dictionary<string, object>? AdditionalAttributes { get; set; }

    /// <inheritdoc />
    protected override void OnParametersSet()
    {
        if (!_jsInitialized)
        {
            return;
        }

        if (Group != _prevGroup ||
            Pull != _prevPull ||
            Put != _prevPut ||
            Sort != _prevSort ||
            Handle != _prevHandle ||
            Filter != _prevFilter ||
            ForceFallback != _prevForceFallback)
        {
            _needsReinit = true;
        }
    }

    /// <inheritdoc />
    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            _ref = DotNetObjectReference.Create(this);
            _module = await JsRuntime.InvokeAsync<IJSObjectReference>(
                "import", "./_content/BlazorBlueprint.Primitives/js/primitives/sortable.js");
            await _module.InvokeVoidAsync(
                "init", Id, Group, Pull, Put, Sort, Handle, Filter, _ref, ForceFallback);
            _jsInitialized = true;
            SnapshotParameters();
        }
        else if (_needsReinit && _module is not null)
        {
            _needsReinit = false;
            await _module.InvokeVoidAsync(
                "init", Id, Group, Pull, Put, Sort, Handle, Filter, _ref, ForceFallback);
            SnapshotParameters();
        }
    }

    private void SnapshotParameters()
    {
        _prevGroup = Group;
        _prevPull = Pull;
        _prevPut = Put;
        _prevSort = Sort;
        _prevHandle = Handle;
        _prevFilter = Filter;
        _prevForceFallback = ForceFallback;
    }

    /// <summary>
    /// Invoked from JavaScript when an item is reordered within this list.
    /// </summary>
    [JSInvokable]
    public async Task OnUpdateJS(int oldIndex, int newIndex)
    {
        _liveAnnouncement = $"Item moved from position {oldIndex + 1} to position {newIndex + 1}.";
        await OnUpdate.InvokeAsync((oldIndex, newIndex));
        StateHasChanged();
    }

    /// <summary>
    /// Invoked from JavaScript when an item is moved out of this list into another.
    /// </summary>
    [JSInvokable]
    public async Task OnRemoveJS(int oldIndex, int newIndex)
    {
        _liveAnnouncement = $"Item removed from position {oldIndex + 1} and placed at position {newIndex + 1} in another list.";
        await OnRemove.InvokeAsync((oldIndex, newIndex));
        StateHasChanged();
    }

    /// <summary>
    /// Invoked from JavaScript when an item from a connected list is dropped into this list.
    /// </summary>
    [JSInvokable]
    public async Task OnAddJS(int oldIndex, int newIndex)
    {
        _liveAnnouncement = $"Item received at position {newIndex + 1}.";
        await OnAdd.InvokeAsync((oldIndex, newIndex));
        StateHasChanged();
    }

    /// <inheritdoc />
    public async ValueTask DisposeAsync()
    {
        GC.SuppressFinalize(this);

        if (_module is not null)
        {
            try
            {
                await _module.InvokeVoidAsync("destroy", Id);
                await _module.DisposeAsync();
            }
            catch (Exception ex) when (ex is JSDisconnectedException or TaskCanceledException or ObjectDisposedException)
            {
                // Expected during circuit disconnect
            }
        }

        _ref?.Dispose();
    }
}
