#!/bin/bash

# Release script for BlazorUI.Primitives
# Usage: ./scripts/release-primitives.sh <version>
# Example: ./scripts/release-primitives.sh 1.6.2

set -e  # Exit on error

PACKAGE_NAME="primitives"
PROJECT_PATH="src/BlazorUI.Primitives"
COLOR_GREEN='\033[0;32m'
COLOR_RED='\033[0;31m'
COLOR_YELLOW='\033[1;33m'
COLOR_CYAN='\033[0;36m'
COLOR_RESET='\033[0m'

COMMITS_MADE=0

# Check if version argument is provided
if [ -z "$1" ]; then
    echo -e "${COLOR_RED}Error: Version argument required${COLOR_RESET}"
    echo "Usage: ./scripts/release-primitives.sh <version>"
    echo "Example: ./scripts/release-primitives.sh 1.6.2"
    exit 1
fi

VERSION=$1
TAG_NAME="${PACKAGE_NAME}/v${VERSION}"
RELEASE_BRANCH="${PACKAGE_NAME}/release/v${VERSION}"

# Validate semantic version format (basic check)
if ! [[ $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.-]+)?$ ]]; then
    echo -e "${COLOR_RED}Error: Invalid version format${COLOR_RESET}"
    echo "Version must follow semantic versioning (e.g., 1.0.0 or 1.0.0-beta.4)"
    exit 1
fi

# Check if we're in the right directory
if [ ! -d "$PROJECT_PATH" ]; then
    echo -e "${COLOR_RED}Error: Project directory not found: $PROJECT_PATH${COLOR_RESET}"
    echo "Make sure you're running this script from the repository root"
    exit 1
fi

# Check for uncommitted changes
if ! git diff-index --quiet HEAD --; then
    echo -e "${COLOR_RED}Error: You have uncommitted changes${COLOR_RESET}"
    echo "Please commit or stash your changes before creating a release"
    git status --short
    exit 1
fi

# Check if tag already exists
if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
    echo -e "${COLOR_RED}Error: Tag $TAG_NAME already exists${COLOR_RESET}"
    echo "Use a different version number or delete the existing tag first"
    exit 1
fi

# Check if release branch already exists
if git rev-parse "$RELEASE_BRANCH" >/dev/null 2>&1; then
    echo -e "${COLOR_RED}Error: Release branch $RELEASE_BRANCH already exists${COLOR_RESET}"
    echo "Delete the existing branch first: git branch -D $RELEASE_BRANCH"
    exit 1
fi

# Show what we're about to do
echo -e "${COLOR_YELLOW}═══════════════════════════════════════════════════${COLOR_RESET}"
echo -e "${COLOR_YELLOW}Release Summary${COLOR_RESET}"
echo -e "${COLOR_YELLOW}═══════════════════════════════════════════════════${COLOR_RESET}"
echo -e "Package:  ${COLOR_GREEN}BlazorUI.Primitives${COLOR_RESET}"
echo -e "Version:  ${COLOR_GREEN}${VERSION}${COLOR_RESET}"
echo -e "Branch:   ${COLOR_CYAN}${RELEASE_BRANCH}${COLOR_RESET}"
echo -e "Tag:      ${COLOR_GREEN}${TAG_NAME}${COLOR_RESET}"
echo -e "${COLOR_YELLOW}═══════════════════════════════════════════════════${COLOR_RESET}"
echo ""

# Confirm with user
read -p "Proceed with release? (y/N): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo -e "${COLOR_YELLOW}Release cancelled${COLOR_RESET}"
    exit 0
fi

# Create release branch
echo ""
echo -e "${COLOR_CYAN}Creating release branch: $RELEASE_BRANCH${COLOR_RESET}"
git checkout -b "$RELEASE_BRANCH"

# No additional checks needed for primitives currently
# Future: Add any pre-release checks here

# Create and push tag
echo ""
echo -e "${COLOR_GREEN}Creating tag: $TAG_NAME${COLOR_RESET}"
git tag -a "$TAG_NAME" -m "Release BlazorUI.Primitives v${VERSION}"

echo -e "${COLOR_GREEN}Pushing release branch and tag to GitHub...${COLOR_RESET}"
git push origin "$RELEASE_BRANCH"
git push origin "$TAG_NAME"

# Create PR if commits were made
if [ $COMMITS_MADE -gt 0 ]; then
    echo ""
    echo -e "${COLOR_CYAN}Creating PR to merge release changes back to main...${COLOR_RESET}"
    PR_URL=$(gh pr create \
        --base main \
        --head "$RELEASE_BRANCH" \
        --title "chore: merge release changes from $TAG_NAME" \
        --body "$(cat <<EOF
## Release Changes

This PR merges changes made during the release of **BlazorUI.Primitives v${VERSION}** back to main.

**Commits made during release:** $COMMITS_MADE

---
*Auto-generated by release script*
EOF
)")
    echo -e "${COLOR_GREEN}PR created: $PR_URL${COLOR_RESET}"
else
    echo ""
    echo -e "${COLOR_CYAN}No additional commits made during release - no PR needed${COLOR_RESET}"
    # Clean up release branch since no changes
    git checkout main
    git branch -D "$RELEASE_BRANCH"
    git push origin --delete "$RELEASE_BRANCH" 2>/dev/null || true
fi

echo ""
echo -e "${COLOR_GREEN}═══════════════════════════════════════════════════${COLOR_RESET}"
echo -e "${COLOR_GREEN}✓ Release initiated successfully!${COLOR_RESET}"
echo -e "${COLOR_GREEN}═══════════════════════════════════════════════════${COLOR_RESET}"
echo ""
echo "GitHub Actions will now:"
echo "  1. Build the project"
echo "  2. Pack the NuGet package"
echo "  3. Publish to NuGet.org"
echo ""
echo "Monitor the workflow at:"
echo "  https://github.com/blazorui-net/ui/actions"
echo ""
